name: PHP-BIASA-001

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v2 
  
=======
    - uses: actions/checkout@v2
  deploy:
   needs: [tests]
   runs-on: ubuntu-latest
   
   steps:
   - name: 'SSH TEST DEPLOY'
     uses: appleboy/ssh-action@master
     with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      password : ${{ secrets.PASSWORD }}
      port: 22
      scripts: |
         cd /autodeploy/test-lagi
         git pull origin master
         git status
         ls -lah
    
  

    
     

