name: PHP-BIASA-001

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  deploy:
   needs: [tests]
   runs-on: ubuntu-latest
   
   steps:
   - name: 'SSH TEST DEPLOY'
     uses: appleboy/ssh-action@master
     with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.PRIVATE_KEY }}
      port: 22
      scripts: |
         cd /autodeploy
         ls -lah
    
  

    
     

   

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
